E-SourcingMicroService/ESourcing.UI/Models/AuctionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace ESourcing.UI.Models
{
    public class AuctionViewModel
    {
        public string Id { get; set; }

        [Required(ErrorMessage = "Please fill name")]

        public string Name { get; set; }

        [Required(ErrorMessage = "Please fill Description")]

        public string Description { get; set; }

        [Required(ErrorMessage = "Please fill ProductId")]

        public string ProductId{ get; set; }
        [Required(ErrorMessage = "Please fill Quantity")]

        public int Quantity{ get; set; }
        public DateTime StartedAt{ get; set; }

        [Required(ErrorMessage = "Please fill FinishedAt")]

        public DateTime FinishedAt { get; set; }
        public DateTime CreatedAt { get; set; }

        public int Status { get; set; }

        public int SellerId { get; set; }

        public List<String> IncludedSellers { get; set; }
    }
}

E-SourcingMicroService/ESourcing.UI/Controllers/AuctionController.cs
using ESourcing.Core.ResultModels;
using ESourcing.Infrastructure.Repositories.Base;
using ESourcing.UI.Clients;
using ESourcing.UI.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ESourcing.UI.Controllers
{
    public class AuctionController : Controller
    {

        readonly IUserRepository _userRepository;
        readonly ProductClient _productClient;
        readonly AuctionClient _auctionClient;
        readonly BidClient _bidClient;

        public AuctionController(IUserRepository userRepository ,ProductClient productClient ,AuctionClient auctionClient, BidClient bidClient)
        {
            _userRepository = userRepository;
            _productClient = productClient;
            _auctionClient = auctionClient;
            _bidClient = bidClient;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _auctionClient.GetAuctionsAsync();

            if(result.IsSuccess)
            {
                return View(result.Data);
            }

            return View(new List<AuctionViewModel>());
        }

        public async Task<IActionResult> Create()
        {

            //TODO:Product GetAll
            var productList = await _productClient.GetProductsAsync();
            if(productList.IsSuccess)
            {
                ViewBag.ProductList = productList.Data;
            }

            var userList = await _userRepository.GetAllAsync();
            ViewBag.UserList = userList;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AuctionViewModel model)
        {
            model.Status = 0;
            model.CreatedAt = DateTime.Now;

            var createAuction = await _auctionClient.CreateAuctionAsync(model);
             if(createAuction.IsSuccess)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public async Task<IActionResult> Detail(string id)
        {
            AuctionBidsViewModel model = new AuctionBidsViewModel();

            
            var auction = await _auctionClient.GetAuctionByIdAsync(id);
            var bidList = await _bidClient.GetAllBidByAuctionIdAsync(id);


            model.SellerUserName = HttpContext.User?.Identity.Name;
            model.Email = HttpContext.User?.FindFirstValue(ClaimTypes.Email);
            model.ID = auction.Data.ID;
            model.ProductId = auction.Data.ProductId;
            model.Bids = bidList.Data;
            var isAdmin = HttpContext.Session.GetString("IsAdmin");
            model.isAdmin = Convert.ToBoolean(isAdmin);


            return View(model);
        }

        [HttpPost]
        public async Task<Result<string>> SendBid(BidViewModel model)
        {
            model.CreatedAt = DateTime.Now;
            var sendBidResponse = await _bidClient.SendBid(model);

            return sendBidResponse;
        }

        [HttpPost]
        public async Task<Result<string>> CompleteBid(BidViewModel model)
        {
            var completeBidResponse = await _auctionClient.CompleteAuction(model.AuctionId);

            return completeBidResponse;
        }
    }
}

E-SourcingMicroService/ESourcing.UI/Views/Auction/Create.cshtml
@model AuctionViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="card card-primary card-outline">
        <div class="card-body">
            <h4>Auction Create Page Step</h4>
            <div class="row">
                <div class="col-5 col-sm-3">
                    <div class="nav flex-column nav-tabs h-100" id="vert-tabs-tab" role="tablist" aria-orientation="vertical">
                        <a class="nav-link active" id="vert-tabs-home-tab" data-toggle="pill" href="#vert-tabs-home" role="tab" aria-controls="vert-tabs-home" aria-selected="true">General Info</a>
                        <a class="nav-link" id="vert-tabs-profile-tab" data-toggle="pill" href="#vert-tabs-profile" role="tab" aria-controls="vert-tabs-profile" aria-selected="false">Product Select</a>
                        <a class="nav-link" id="vert-tabs-messages-tab" data-toggle="pill" href="#vert-tabs-messages" role="tab" aria-controls="vert-tabs-messages" aria-selected="false">Seller Select</a>

                    </div>
                </div>
                <div class="col-7 col-sm-9">
                    <div class="tab-content" id="vert-tabs-tabContent">

                        <div id="vert-tabs-home" class="text-left show active tab-pane fade card card-primary" role="tabpanel" aria-labelledby="vert-tabs-home-tab">
                            <div class="card-header">
                                <h3 class="card-title">General Info Inputs</h3>
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="Name">Auction Name</label>
                                    @Html.TextBoxFor(x => x.Name, new { placeholder = "Enter Auction Name", @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label for="Description">Auction Description</label>
                                    @Html.TextBoxFor(x => x.Description, new { placeholder = "Enter Auction Description", @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label for="Description">Auction Quantity</label>
                                    @Html.TextBoxFor(x => x.Quantity, new { placeholder = "Enter Quantity", @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label>Start Date:</label>
                                    <div class="input-group date" id="StartedAt" data-target-input="nearest">
                                        <input type="datetime-local" asp-for="StartedAt" class="form-control datetimepicker-input" />

                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Finish Date:</label>
                                    <div class="input-group date" id="FinishedAt" data-target-input="nearest">
                                        <input type="datetime-local" asp-for="FinishedAt" class="form-control datetimepicker-input" />

                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="text-left tab-pane fade card card-warning" id="vert-tabs-profile" role="tabpanel" aria-labelledby="vert-tabs-profile-tab">
                            <div class="card-header">
                                <h3 class="card-title">Product Info Input</h3>
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    @Html.DropDownListFor(l => l.ProductId, new SelectList(ViewBag.ProductList, "Id", "Name"), "Please Select Product", new { @class = "custom-select form-control col-sm-6" })
                                </div>
                            </div>
                        </div>
                        <div class="text-left tab-pane fade card card-danger" id="vert-tabs-messages" role="tabpanel" aria-labelledby="vert-tabs-messages-tab">
                            <div class="card-header">
                                <h3 class="card-title">Seller Info Input</h3>
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    @Html.DropDownListFor(l => l.SellerId, new SelectList(ViewBag.UserList, "Id", "FirstName"), "Please Select Seller", new { @class = "custom-select form-control col-sm-6" })
                                </div>
                                <div class="clearfix form-actions">
                                    <div class="col-md-offset-3 col-md-9">
                                        <input type="submit" value="Create Auction" class="btn btn-info col-xs-3" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<!-- jQuery -->
<script src="../../plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="../../dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="../../dist/js/demo.js"></script>

E-SourcingMicroService/ESourcing.UI/Views/Auction/Detail.cshtml
@model AuctionBidsViewModel


@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-6">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Quick Auction</h3>
            </div>
            <form method="post">
                <div class="card-body">
                    <div class="form-group">
                        <label for="exampleInputPrice">Price</label>
                        <input type="number" min="0" class="form-control" id="exampleInputPrice" placeholder="Enter Price" />
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" id="sendButton" class="btn btn-primary">Submit</button>
                    <button type="submit" id="finishButton" class="btn btn-primary">Finish RFQ</button>
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-6">
        <div style="background-color:darkgrey; color:white;" class="card-header">
            <h3 class="card-title">Active Auction Detail</h3>
        </div>
        @Html.HiddenFor(x => x.ID, new { id = "AuctionId" } /*AuctionId*/)
        @Html.HiddenFor(x => x.ProductId)
        @Html.HiddenFor(x => x.SellerUserName)
        @Html.HiddenFor(x => x.Email)

        <div class="card-body mt-2" style="padding:0;">
            <table id="exampleAuction" class="table table-bordered table-hover">
                <thead>
                    <tr style="background-color:skyblue; color:papayawhip;">
                        <th>Auction User Name</th>
                        <th>Price</th>
                        <th>Quantity</th>
                    </tr>
                </thead>
                <tbody class="bidLine">
                    @if (Model.Bids.Any())
                    {
                        @foreach (var item in Model.Bids)
                        {
                            <tr>
                                <td>@item.SellerUserName</td>
                                <td>@item.Price $</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>


<script src="~/lib/microsoft-signalr/signalr.js"></script>
<script src="~/js/Views/RFQ/Detail.js"></script>

E-SourcingMicroService/ESourcing.UI/Views/Auction/Index.cshtml
@model IEnumerable<AuctionViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<div class="row mt-4">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Active Auction List</h3>
            </div>
            <div class="card-body">
                <table id="example1" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Quantity</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var item in Model)
                        {
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.Description</td>
                            <td>@item.Quantity</td>
                            <td>@item.StartedAt.ToShortDateString()</td>
                            <td>@item.FinishedAt.ToShortDateString()</td>
                            <td>
                                @if (item.Status == 0)
                                {
                                    <a asp-controller="Auction" asp-action="Detail" asp-route-Id="@item.Id" class="btn btn-warning text-white " style="font-size: 13px;  padding: 6px 0; width: 100px; ">Detail</a>
                                }
                                 else
                                {
                                    <a onclick="return false" class="btn  text-white" style="font-size: 13px; background-color: #ff8e8e; cursor: default; padding: 6px 0; width: 100px;" disabled>Closed</a>
                                }

                            </td>
                        </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>